package api_test

import (
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"
)

func TestFindConstructorOrientedDomainFactories(t *testing.T) {
	t.Parallel()

	fixtureWant := []string{
		"example.com/policyfixture/generated.NewGeneratedActivity",
		"example.com/policyfixture/public.NewConcreteQuestion",
		"example.com/policyfixture/public.NewConsoleReporter",
		"example.com/policyfixture/public.NewDirectActivity",
		"example.com/policyfixture/public.NewDirectInteraction",
		"example.com/policyfixture/public.NewDirectQuestion",
		"example.com/policyfixture/public.NewFluentBuilder",
		"example.com/policyfixture/public.NewNamedActivity",
		"example.com/policyfixture/public.NewNamedQuestion",
		"example.com/policyfixture/public.NewPointerActivity",
		"example.com/policyfixture/public.NewQuestionFromAnotherFile",
	}
	tests := []struct {
		name      string
		moduleDir func(*testing.T) string
		want      []string
	}{
		{
			name:      "detects type-aware factories across public production files",
			moduleDir: writePolicyFixture,
			want:      fixtureWant,
		},
		{
			name:      "preserves only package-qualified issue exclusions",
			moduleDir: repositoryRoot,
			want:      nil,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			got, err := findConstructorOrientedDomainFactories(test.moduleDir(t))
			if err != nil {
				t.Fatalf("scan module: %v", err)
			}
			sort.Strings(got)
			sort.Strings(test.want)
			if strings.Join(got, "\n") != strings.Join(test.want, "\n") {
				t.Fatalf("constructor-oriented factories mismatch\nwant:\n%s\n\ngot:\n%s", strings.Join(test.want, "\n"), strings.Join(got, "\n"))
			}
		})
	}
}

func writePolicyFixture(t *testing.T) string {
	t.Helper()

	root := t.TempDir()
	repository := repositoryRoot(t)
	files := map[string]string{
		"go.mod": "module example.com/policyfixture\n\ngo 1.23.4\n\nrequire github.com/verity-bdd/verity-bdd v0.0.0\n\nreplace github.com/verity-bdd/verity-bdd => " + filepath.ToSlash(repository) + "\n",
		"public/domain.go": `package public

import (
	"context"

	verity "github.com/verity-bdd/verity-bdd"
)

type question struct{}
func (question) Description() string { return "question" }
func (question) AnsweredBy(context.Context, verity.Actor) (string, error) { return "", nil }

type activity struct{}
func (*activity) Description() string { return "activity" }
func (*activity) PerformAs(context.Context, verity.Actor) error { return nil }
func (*activity) FailureMode() verity.FailureMode { return verity.FailFast }

type NamedQuestion interface { verity.Question[int] }
type NamedActivity interface { verity.Activity }

type FluentBuilder struct{}
func (*FluentBuilder) WithValue(string) *FluentBuilder { return nil }
func (*FluentBuilder) Finish() verity.Activity { return nil }

func NewDirectQuestion() verity.Question[string] { return question{} }
func NewDirectActivity() verity.Activity { return nil }
func NewDirectInteraction() verity.Interaction { return nil }
func NewConcreteQuestion() question { return question{} }
func NewPointerActivity() *activity { return nil }
func NewNamedQuestion() NamedQuestion { return nil }
func NewNamedActivity() NamedActivity { return nil }
func NewFluentBuilder() *FluentBuilder { return nil }
func NewConsoleReporter() verity.Activity { return nil }
func DomainQuestion() verity.Question[string] { return question{} }
func NewUnrelated() string { return "" }
`,
		"public/another.go": `package public

import (
	"context"
	verity "github.com/verity-bdd/verity-bdd"
)

type anotherQuestion struct{}
func (anotherQuestion) Description() string { return "question" }
func (anotherQuestion) AnsweredBy(context.Context, verity.Actor) (bool, error) { return false, nil }
func NewQuestionFromAnotherFile() anotherQuestion { return anotherQuestion{} }
`,
		"public/domain_test.go": `package public
import verity "github.com/verity-bdd/verity-bdd"
func NewTestOnlyActivity() verity.Activity { return nil }
`,
		"internal/hidden.go": `package internal
import verity "github.com/verity-bdd/verity-bdd"
func NewInternalActivity() verity.Activity { return nil }
`,
		"mocks/mock_activity.go": `package mocks
import verity "github.com/verity-bdd/verity-bdd"
func NewMockActivity() verity.Activity { return nil }
`,
		"generated/generated.go": `// Code generated by fixture. DO NOT EDIT.
package generated
import verity "github.com/verity-bdd/verity-bdd"
func NewGeneratedActivity() verity.Activity { return nil }
`,
	}
	for name, contents := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("create fixture directory: %v", err)
		}
		if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
			t.Fatalf("write fixture %s: %v", name, err)
		}
	}
	return root
}

func repositoryRoot(t *testing.T) string {
	t.Helper()

	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("could not locate policy detector test")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(filename), "..", ".."))
}
